FoodSellerProject/Controllers/FoodController.cs
using Businness_Layer.Concrete;
using Data_Access_Layer.EntityFramework;
using Entitiy_Layer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FoodSellerProject.Controllers
{
    public class FoodController : Controller
    {
        FoodManager fm = new FoodManager(new EfFoodDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public IActionResult Index()
        {
            var Foodvalues = fm.GetList();
            return View(Foodvalues);
        }
        [HttpGet]
        public IActionResult AddFood() 
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valuecategory;
            return View();
        }
        [HttpPost]
        public IActionResult AddFood(Foods p) 
        {
            fm.foodAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditFood(int id) 
        {
			List<SelectListItem> valuecategory = (from x in cm.GetList()
												  select new SelectListItem
												  {
													  Text = x.CategoryName,
													  Value = x.CategoryID.ToString()
												  }).ToList();
			ViewBag.vlc = valuecategory;

			var foodvalues = fm.GetByID(id);
            return View(foodvalues);
        }
        [HttpPost]
		public IActionResult EditFood(Foods p)
        {
			fm.foodUpdate(p);
			return RedirectToAction("Index");
		}

        public IActionResult DeleteFood(int id)
        {
            var foodvalues= fm.GetByID(id);
            foodvalues.FoodStatus = false;
            fm.foodDelete(foodvalues);
            return RedirectToAction("Index");
        }


	}
}

FoodSellerProject/Views/Food/AddFood.cshtml
@using Entitiy_Layer.Concrete
@model Entitiy_Layer.Concrete.Foods

@{
    ViewData["Title"] = "AddFood";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Ürün Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddFood", "Food", FormMethod.Post))
{
    <div class="form-gruop">
        @Html.Label("Ürün Adı")
        @Html.TextBoxFor(x=> x.FoodName, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FoodName)
        <br />
        @Html.Label("Ürün Stoğu")
        @Html.TextBoxFor(x=> x.FInStock, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FInStock)
        <br />
        @Html.Label("Ürün Fiyatı")
        @Html.TextBoxFor(x=> x.FUnitPrice, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FUnitPrice)
        <br />
        @Html.Label("Üretim Tarihi")
        @Html.TextBoxFor(x=> x.FoodPDate, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FoodPDate)
        <br />
        @Html.Label("Son Tütekim Tarihi")
        @Html.TextBoxFor(x=> x.FoodLCD, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FoodLCD)
        <br />
        @Html.Label("Raf Ömrü")
        @Html.TextBoxFor(x=> x.FoodSLT, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.FoodSLT)
        <br />
        @Html.Label("Ürün'ün Kategorisi")
        @Html.DropDownListFor(x=> x.CategoryID,(List<SelectListItem>)ViewBag.vlc, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.CategoryID)
        <br /> <br />
        <button class="btn btn-info">Ürün Ekle</button>
    </div>
}

FoodSellerProject/Views/Food/EditFood.cshtml
@model Entitiy_Layer.Concrete.Foods
@{
	ViewData["Title"] = "EditFood";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Ürün Güncelleme Sayfası</h1>

@using (Html.BeginForm("EditFood", "Food", FormMethod.Post))
{
	<div class="form-gruop">
		@Html.Label("Ürün ID")
		@Html.TextBoxFor(x=> x.FoodID, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FoodID)
		<br />
		@Html.Label("Ürün Adı")
		@Html.TextBoxFor(x=> x.FoodName, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FoodName)
		<br />
		@Html.Label("Ürün'ün Raf Ömrü")
		@Html.TextBoxFor(x=> x.FoodSLT, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FoodSLT)
		<br />
		@Html.Label("Ürün'ün STT")
		@Html.TextBoxFor(x=> x.FoodLCD, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FoodLCD)
		<br />
		@Html.Label("Ürün'ün Üretim Tarihi")
		@Html.TextBoxFor(x=> x.FoodPDate, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FoodPDate)
		<br />
		@Html.Label("Ürün'ün Fiyatı")
		@Html.TextBoxFor(x=> x.FUnitPrice, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FUnitPrice)
		<br />
		@Html.Label("Ürün'ün Stok Durumu")
		@Html.TextBoxFor(x=> x.FInStock, new {@class = "form-control"})
		@Html.ValidationMessageFor(x=> x.FInStock)
		<br />
		@Html.Label("Categori Adı")
		@Html.DropDownListFor(x=> x.CategoryID,(List<SelectListItem>)ViewBag.vlc, new {@class= "form-control" })
		<br /> <br />
		<button class="btn btn-success">Ürün'ü Düzenle</button>
	</div>
}

FoodSellerProject/Views/Food/Index.cshtml
@using Entitiy_Layer.Concrete
@model List<Foods>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{string color = "";}
@{string statuscolor = "";}
@{string statusset = "";}
@{string statussetcolor = "";}
@{string date = "";}
@{string image = "";}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>
	<!-- Main content -->
	<section class="content">
		<!-- Default box -->
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Ürün İşlemleri</h3>
				<div class="card-tools">
					<button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
						<i class="fas fa-minus"></i>
					</button>
					<button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
						<i class="fas fa-times"></i>
					</button>
				</div>
			</div>
			<div class="card-body p-0">
				<table class="table table-striped projects">
					<thead>
						<tr>
							<th style="width: 20%">
								Ürün Adı
							</th>
							<th style="width: 15%">
								Kategorisi
							</th>
							<th style="width: 15%">
								Durum
							</th>
							<th style="width: 15%">
								Ürün Fiyatı
							</th>
							<th style="width: 15%">
								Stok Durumu
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							@*<--------------------------------->*@
							@*Kategori Renkleri*@
							if (item.Category.CategoryName=="Meyve")
							{
								color = "badge badge-warning";
							}
							if (item.Category.CategoryName=="Sebze")
							{
								color = "badge badge-success";
							}
							if (item.Category.CategoryName=="Bakliyat")
							{
								color = "badge badge-dark";
							}
							if (item.Category.CategoryName=="Süt ve Süt Ürünleri")
							{
								color = "badge badge-light";
							};
							@*<--------------------------------->*@

							@*Durum Classı*@
							@*<+++++++++++++++++++++++++++++++++>*@
							if (item.FoodStatus == true)
							{
								statuscolor = "badge badge-info";
							}
							if (item.FoodStatus == false)
							{
								statuscolor = "badge badge-danger";
							}
							if (item.FoodStatus == true)
							{
								statussetcolor = "btn btn-danger btn-sm";
								statusset = "Pasif";
							}
							if (item.FoodStatus == false)
							{
								statussetcolor = "btn btn-warning btn-sm";
								statusset = "Aktif";
							}
							@*<+++++++++++++++++++++++++++++++++>*@

							@*Ürün Tarihleri*@
							@*<*********************************>*@
							if (item.Category.CategoryName == "Meyve")
							{
								date = "Raf Ömrü : " + (((DateTime)item.FoodSLT).ToString("dd - MMM - yyyy"));
							}
							if (item.Category.CategoryName == "Sebze")
							{
								date = "Raf Ömrü : " + (((DateTime)item.FoodSLT).ToString("dd - MMM - yyyy"));
							}
							if (item.Category.CategoryName == "Bakliyat")
							{
								date = "Üretim Tarihi : " + (((DateTime)item.FoodPDate).ToString("dd - MMM - yyyy"));
							}
							if (item.Category.CategoryName == "Süt ve Süt Ürünleri")
							{
								date = "STT : " + (((DateTime)item.FoodLCD).ToString("dd - MMM - yyyy"));

							};
							@*<*********************************>*@

							@*Kategori Görselleri*@
							@*<.................................>*@
							if (item.Category.CategoryName == item.FoodName)
							{
								image = item.Category.CategoryImageURL;
							}
							@*<..................................>*@
							
							<tr>
								<td>
									<a>
										@item.FoodName <img alt="Avatar" class="note-icon-table" src="@item.Category.CategoryImageURL">
									</a>
									<br />
									<small>
										@*@(((DateTime)item.FoodLCD).ToString("dd-MMM-yyyy"));<br />*@
										@date
										@*@(((DateTime)item.FoodPDate).ToString("dd-MMM-yyyy"));<br />*@
									</small>
								</td>
								<td>
									<ul class="list-inline">
										<li class="list-inline-item">
											<span class="@color">@item.Category.CategoryName</span>

											@*<img alt="Avatar" class="table-avatar" src="@item.Category.CategoryImageURL">*@
										</li>
									</ul>
								</td>
								<td>
									<span class="@statuscolor">@item.FoodStatus</span>
								</td>
								<td>
									<span class="badge badge-success">@item.FUnitPrice</span>
								</td>
								<td>
									<span class="badge badge-secondary">@item.FInStock</span>
								</td>
								<td class="project-actions text-center">
									<a class="btn btn-primary btn-sm" href="/Order/OrderByFood/@item.FoodID">
										Siparişler
									</a>
									<a class="btn btn-info btn-sm" href="/Food/EditFood/@item.FoodID">
										Düzenle
									</a>
									<a class="@statussetcolor" href="/Food/DeleteFood/@item.FoodID">
										@statusset
									</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
		<!-- /food-Insert -->
	</section>
</body>
</html>
<a href="/Food/AddFood" class="btn btn-info">Yeni Ürün Ekle</a>