FoodSellerProject/Controllers/AdminCategoryController.cs
using Businness_Layer.Concrete;
using Businness_Layer.ValidationRules;
using Data_Access_Layer.EntityFramework;
using Entitiy_Layer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace FoodSellerProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public IActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public IActionResult AddCategory() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category p) 
        {
            CategoryValidator categoryvalidator = new CategoryValidator();
            ValidationResult result = categoryvalidator.Validate(p);

            if (result.IsValid)
            {
                cm.categoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View();
        }
        public IActionResult DeleteCategory(int id) 
        {
            var categoryvalue = cm.GetByID(id);
            cm.categoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCategory(int id) 
        {
            var categoryvalue = cm.GetByID(id);

            return View(categoryvalue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p) 
        {
            cm.categoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

FoodSellerProject/Views/AdminCategory/AddCategory.cshtml
@model Entitiy_Layer.Concrete.Category
@{
    ViewData["Title"] = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-gruop">
        @Html.Label("Kategori Adı")
        @Html.TextAreaFor(x=> x.CategoryName, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.CategoryName)
        <br /> <br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x=> x.CDescription, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.CDescription)
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

FoodSellerProject/Views/AdminCategory/EditCategory.cshtml
@model Entitiy_Layer.Concrete.Category
@{
    ViewData["Title"] = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/>
<h1>Categori Güncelleme Sayfası</h1>

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-gruop">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x=> x.CategoryID, new {@class = "form-control"})
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x=> x.CategoryName, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.CategoryName)
        <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x=> x.CDescription, new {@class = "form-control"})
        @Html.ValidationMessageFor(x=> x.CDescription)

        <br /> <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

FoodSellerProject/Views/AdminCategory/Index.cshtml
@using Entitiy_Layer.Concrete
@model List<Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori</th>
        <th>Kategori Görseli</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td><img alt="Avatar" class="note-icon-table" src="@item.CategoryImageURL"></td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-success">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Siparişler</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>